### ISSUE TITLE
Payment Apps are not installed but still shwing that apps are available

### ISSUE THREAD

**Issue by ajay-tamhankar** [abhishekbardolia/flutter_pay_upi#3]
I have uninstalled Phonepe App but it is still giving me Phonepe as installed in iOS.
same issue for amazon pay
Please help

**Comment by abhishekbardolia** [comment]
Hello @ajay-tamhankar , unlike Android, iOS does not provide information on which UPI apps are installed on a device. Therefore, iOS uses predefined values for this purpose.
